baseURL = "https://opencensus-website-snapshot.firebaseapp.com/"
languageCode = "en-us"
title = "OpenCensus"
theme = "census"

[params]
  description = "A stats collection and distributed tracing framework"



